name: Build & Test
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run cypress:ci
